######################################################################
##
## Filename: sdram_fifo_tb.do
##
##  Auto generated by Project Navigator for Behavioral Simulation
##
##  ---------------------DONOT EDIT THIS FILE-------------------------
##  You may want to add additional commands to control the simulation
##  in the user specific do file (<module>.udo) which is automatically
##  generated in the project directory and will not be removed on
##  subsequent simulation flows run from Project Navigator.
transcript on
if {[file exists rtl_work]} {
	vdel -lib rtl_work -all
}
vlib rtl_work
vmap work rtl_work


vlog  "../ipcore/sdrm_fifo.v"
vlog  "../src/defination.v"
vlog  "../sim/fifo_sim.v"
#
#vsim -voptargs="+acc" -t 1ps -lib work work.fifo_sim 
vsim -t 1ps -L lpm_ver -L altera_ver -L altera_mf_ver -L sgate_ver -L rtl_work -L work fifo_sim

add wave -divider 
add wave -noupdate -color green -radix hexadecimal /*   

#
#
# Set the window types
#
view wave
view structure
view signals
#
# Run simulation for this time
#
#run 10us
#
# End
#
